export default [
  {
    files: ["**/*.js"],
    languageOptions: {
      ecmaVersion: 2022,
      sourceType: "script",
      globals: {
        API_BASEURL: "readonly",
        BASEURL: "readonly",
        OCTOPRINT_VIEWMODELS: "writable",
        PNotify: "readonly",
        $: "readonly",
        Audio: "readonly",
        Blob: "readonly",
        Date: "readonly",
        Math: "readonly",
        Object: "readonly",
        RegExp: "readonly",
        alert: "readonly",
        confirm: "readonly",
        console: "readonly",
        document: "readonly",
        encodeURIComponent: "readonly",
        gettext: "readonly",
        isNaN: "readonly",
        parseInt: "readonly",
        ko: "readonly",
        ngettext: "readonly",
        setTimeout: "readonly",
        clearInterval: "readonly",
        setInterval: "readonly",
        window: "readonly",
      },
    },
    rules: {
      "no-unused-vars": "off",
    },
  },
];
